controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

health_check:
    path: /health
    controller: App\Controller\HealthCheckController
    methods: [ GET ]